---
title: "Child Blood Lead Levels Nationally and in Philadelphia"
subtitle: "BMIN503/EPID600 Final Project"
author: "Ashley Trocle"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

## Overview {#sec-overview}

Materials for this project can be found here: [GitHub Repository](https://github.com/atrocle/BMIN503_Final_Project_Trocle)

## Introduction {#sec-introduction}

The issue:

Exposure to elevated lead levels during childhood is a critical environmental and public health issue. Lead is a neurotoxin that impacts on neurological and behavioral development in child. Measured most commonly via blood lead levels, there is no safe level of lead exposure for children. Even low levels of lead exposure during developmental stages can lead to lifelong adverse effects on cognitive function and attention.

A primary source of exposure for young children is deteriorating lead based paint, which is still present in many homes despite a national ban in 1978. Children commonly ingest paint chips or paint dust. Both acute and chronic exposure to lead can be dangerous.

Elevated blood lead levels continue to disproportionately affect marginalized communities, especially low-income and minority groups who often live in older, non-remidiated housing. Addressing lead exposure is key to addressing health disparities nationally and in our communities.

The Policy:

A number of federal, state and local policies have dramatically reduces the rates of lead exposures in the past 50 years.

National:

1974: Safe Drinking Water Act

1978: Lead based paints were banned in residences

1999: Lead Safe Housing Rule

2021:

Local:

2011: Philadelphia Lead Paint Disclosure Law -

2019: Expansion of the 2011 law to include all rental properties, not only those with children

This Project:

Using data from the NHANES, ASC, OpenDataPhilly

This project takes an interdisciplinary approach to better understand lead exposure issues at both national, state and local levels. The project integrates social epidemiology, environmental health, public health and policy analysis to address the complex nature of issues that contribute to lead exposure and the significant impact it can have on children.

## Methods {#sec-methods}

```{r}
#Load Libraries
library(nhanesA)
library(haven)
library(tidycensus)

#NHANES Data

#varlist <- c("DEMO", "HSQ", "HIQ", "MCQ") 
#varlist_years <- paste0(rep(varlist, each = 2), c("_I", "_J"))

#list_all <- sapply(varlist_years, function(x) {data.frame(nhanes(x))}) 

#ACS Data
#housing characteristics
acs.data<- get_acs(geography= "county",
                   year= 2022,
                   variables = c("B25034_002E", "B25034_003E", "B25034_004E",
"B25034_005E", "B25034_006E", "B25034_007E","B25034_008E","B25034_009", "B25034_010E","B25034_011E"),
 output = "wide")

acs.data.phl<- get_acs(geography= "tract",
                   year= 2022,
                   variables = c("B25034_002E", "B25034_003E", "B25034_004E",
"B25034_005E", "B25034_006E", "B25034_007E","B25034_008E","B25034_009", "B25034_010E","B25034_011E"),
                  output = "wide",
                  state="PA",
                  county="Philadelphia")


#OpenDataPhilly Data


```

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.

## Acknowledgements

## References
